// Code generated by "stringer -type=ErrorMessageStrategy -output=error_message_strategy_string.go -linecomment"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OriginalMsg-0]
	_ = x[PrependFullFuncName-1]
	_ = x[PrependFullPkgName-2]
	_ = x[PrependSimpleFuncName-3]
	_ = x[PrependSimplePkgName-4]
}

const _ErrorMessageStrategy_name = "OriginalMessagePrependFullFunctionNamePrependFullPackageNamePrependSimpleFunctionNamePrependSimplePackageName"

var _ErrorMessageStrategy_index = [...]uint8{0, 15, 38, 60, 85, 109}

func (i ErrorMessageStrategy) String() string {
	if i < 0 || i >= ErrorMessageStrategy(len(_ErrorMessageStrategy_index)-1) {
		return "ErrorMessageStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorMessageStrategy_name[_ErrorMessageStrategy_index[i]:_ErrorMessageStrategy_index[i+1]]
}
