// Code generated by "stringer -type=ErrorMessageStrategy -output=error_message_strategy_string.go -linecomment"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OriginalMsg-0]
	_ = x[PrefixFullPkgName-1]
	_ = x[PrefixSimplePkgName-2]
	_ = x[PrefixFullFuncName-3]
	_ = x[PrefixSimpleFuncName-4]
}

const _ErrorMessageStrategy_name = "OriginalMessagePrefixFullPackageNamePrefixSimplePackageNamePrefixFullFunctionNamePrefixSimpleFunctionName"

var _ErrorMessageStrategy_index = [...]uint8{0, 15, 36, 59, 81, 105}

func (i ErrorMessageStrategy) String() string {
	if i < 0 || i >= ErrorMessageStrategy(len(_ErrorMessageStrategy_index)-1) {
		return "ErrorMessageStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorMessageStrategy_name[_ErrorMessageStrategy_index[i]:_ErrorMessageStrategy_index[i+1]]
}
