// Code generated by "stringer -type=ErrorMessageStrategy -output=error_message_strategy_string.go -linecomment"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OriginalMsg-1]
	_ = x[PrependFullFuncName-2]
	_ = x[PrependFullPkgName-3]
	_ = x[PrependSimpleFuncName-4]
	_ = x[PrependSimplePkgName-5]
	_ = x[maxErrorMessageStrategy-6]
}

const _ErrorMessageStrategy_name = "OriginalMessagePrependFullFunctionNamePrependFullPackageNamePrependSimpleFunctionNamePrependSimplePackageNameErrorMessageStrategy(6)"

var _ErrorMessageStrategy_index = [...]uint8{0, 15, 38, 60, 85, 109, 132}

func (i ErrorMessageStrategy) String() string {
	i -= 1
	if i < 0 || i >= ErrorMessageStrategy(len(_ErrorMessageStrategy_index)-1) {
		return "ErrorMessageStrategy(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrorMessageStrategy_name[_ErrorMessageStrategy_index[i]:_ErrorMessageStrategy_index[i+1]]
}
